apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config

data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>QA</title>
      </head>
      <body>
        <h1>QA Environment</h1>
        <h2>Kubernetes Testing</h2>
        <p>This environment is used for validation.</p>
      </body>
    </html>
