apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config

data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Development</title>
      </head>
      <body>
        <h1>Development Environment</h1>
        <h2>Welcome to Kubernetes</h2>
        <p>This page is served from a ConfigMap.</p>
      </body>
    </html>
